### ISSUE TITLE
Hero can't move

### ISSUE THREAD

**Issue by csmx123** [Zwolf11/DungeonDrive#1]
With the newest version I've pulled, the hero can't move. I will look into that and figure out what happened.

**Comment by zanzibar528** [comment]
I think he just gets pinned against the 2 walls in the corner because they are boundaries now. At least that what was happening when I pushed. Just attack your way out with "j."

**Comment by csmx123** [comment]
I think the way to compute the collision is creating a problem.
In condition

``` bash
!G.room.walkingSpace[(int)x + 1,(int)y + 1] || !G.room.walkingSpace[(int)x,(int)y] || !G.room.walkingSpace[(int)x,(int)y + 1] || !G.room.walkingSpace[(int)x + 1, (int)y]
```

notice that **_x**_ and **_y**_ indicate the next step the hero/enemy is going to take in double, in that case the condition should simply be **!G.room.walkingSpace[(int)x,(int)y]**. However, changing double into int is not that simple(ex. floor and ceiling problem). I think the best way to do it is to record every object's double boundary and loop through them. That's what I did for enemies. I know it will take a lot of memories, but other than that I don't know what to do, because this game isn't in grid and I can't simply calculate the collision between hero and enemies.

**Comment by zanzibar528** [comment]
Well the actual coordinates of the hero are the top left corner of the hero's circle, so I had to check all the corners to make sure none are moving into a square that isn't in the walking space. I just checked and it works on my computer though, so that's odd. I'll try to use Math.Floor() and see if it works.

**Comment by Zwolf11** [comment]
Originally I planned for the coordinates to be the middle of the circle.
Did someone change it?

**Comment by zanzibar528** [comment]
I didn't change it. Either way, he will inevitably take up more than 1 box, so all of those boxes he is occupying need to be checked in the walkingSpace boolean array. I don't think it'll change whether the coordinates are in the middle, or at some corner.

**Comment by csmx123** [comment]
No, I don't think floor/ceiling would work.

**Comment by zanzibar528** [comment]
Different floor and ceiling functions for room collision detection? Like, if the hero is facing left, check these indices of the boolean array, if he is facing right, check different ones?

**Comment by Zwolf11** [comment]
This all seems very convoluted. I'm sure there's an easier way. Let's talk
about room collision tonight at the meeting. Don't worry about it for now

**Comment by csmx123** [comment]
No, I don't think that would work. For example, hero is above the object but not in the center.(ex. hero coord(0.6,0) and obj coord(0,-1)). If he wants to move down, how would u decide to whether use floor or ceiling? What if the hero's coord is at (0.4,0) and the obj coord at(1,-1)?
