### ISSUE TITLE
got a crash

### ISSUE THREAD

**Issue by csmx123** [Zwolf11/DungeonDrive#2]
When I comment out

``` bash
if((x < 0) || (((int)(x+1)) > G.room.width - 1) || (y < 0) || (((int)(y+1)) > G.room.height - 1) || !G.room.walkingSpace[(int)(x + 1), (int)(y + 1)] || !G.room.walkingSpace[(int)x, (int)y] || !G.room.walkingSpace[(int)x, (int)(y + 1)] || !G.room.walkingSpace[(int)(x + 1), (int)y])
     return false;
```

I got following crash when I'm running outside of the square areas

``` bash
A first chance exception of type 'System.IndexOutOfRangeException' occurred in DungeonDrive.exe
An unhandled exception of type 'System.IndexOutOfRangeException' occurred in DungeonDrive.exe
Additional information: Index was outside the bounds of the array.
```

visual studio indicated that the crash happened at

``` bash
if (G.room.stairSpace[(int)(x + .5), (int)(y + .5)])
```

I don't know if it's because I commented the section or there's a potential bug in the code. Please check.

**Comment by zanzibar528** [comment]
If you want to run outside of the hallways and rooms, go into the room file and comment out the call to the function addBoundaries() in the generateRoom function.  There are multiple places that check values from the arrays for the room, (like the checkcollison code for the stairs right above that line you commented out) so not checking that the hero stays within a valid index is gonna lead to problems.

**Comment by zanzibar528** [comment]
OK I added a bool value at the top of room.cs that will disable the boundaries in an appropriate way. Just flip noBoundaries to true like the comment says if you want to test in an open room.

**Comment by csmx123** [comment]
Ok, I also have another issue. After adding the new knockback, when I get into a small room that consists a lot of enemies, the program will crash after I tried to attack the enemies, and I honestly don't know where the crash is coming from. I've tried to comment my attacking method, enemy collisions, and room collisions one by one. It works when I comment one of them, but when I have all of them running the program will crash in that room. Can you take a look maybe you can help me to figure out.

**Comment by Zwolf11** [comment]
I just made some huge changes to collision and some other stuff, try pulling and trying out the new stuff. Also, it's likely the reason you're crashing is because of how you're handling attacking. You're creating a bunch of threads that are sleeping and causing issues. Thread.sleep seems kinda buggy for many reasons. I think you may need to implement a different way to handle attacking. For instance, if you try to close the program after using the knockback skill, the thread will still be running even though the program is closed.

**Comment by csmx123** [comment]
I don't think it has anything to do with sleep because I didn't even call sleep in my program. Also I've tried to use time tick instead of thread I still got the same crash. I simply go to that room and pressed J. Well I can't think of a better way to move things smoothly besides thread and time tick. Anyways I think I'm going to try the newest collision checking, it might solve the problem.

**Comment by Zwolf11** [comment]
As for what you can do besides Thread.sleep, you could have another function like act() that is called every update except it handles knockbacks and the sort.

**Comment by Zwolf11** [comment]
That would also improve how people are being knocked back through walls because you could just call my new tryMove() method to move the units back and it'll check wall collisions and stuff.

**Comment by csmx123** [comment]
Yes I did try a method that does like "act()", it uses Time.Tick right? Yes I've tried it and it still crashed...I've pulled the newest version and now it won't let me enter one of the rooms...it crashes when I tried to enter, here's the youtube link: http://www.youtube.com/watch?v=EJqZfd4e0_s
And I didn't press anything such as attacks, I simply pressed wasd

**Comment by Zwolf11** [comment]
Well, I did increase the maxStairs and maxEnemies in room.cs because I wanted to see all of my folders since it was only loading 10. Your computer may not be able to handle as much as mine can. As for the update thing, just use my already existent function in logic.cs. Just before every actor's act() is called, just call your knockback methods.

**Comment by csmx123** [comment]
Ok it makes more sense now. I changed the maxenemy back to 15 and the crashes are gone including the previous one in small room. I guess it has problems with the collisions mainly. Well I'm only running windows on a simulator, I guess it can't handle too many enemies.
